import { IAvailableBankData } from "./contracts";
export declare const isBankSelectionAvailable: (countryCode: string, currencyCode: string) => boolean;
export declare const getAvailableBanksByCountry: (countryCode: string | undefined) => IAvailableBankData[];
export declare const getAllAvailableBanks: (countryCode: string | undefined, aquirer: string | undefined) => IAvailableBankData[];
export declare const getImageUrl: (assetBaseUrl: string, provider: string, countryCode?: string | undefined) => string;
export declare const addExpressPayDetailsEventListener: () => void;
export declare const getCountryForQRPlatbaBank: (countryCode: string) => boolean;
export declare const getExpressPayDetailsKeys: () => Map<string, string>;
export declare const getExpressPayQueryParams: (expressPayOptions: any, details?: any) => string;
export declare const formatBillingAddress: (fields: any, state: string) => string;
export declare const formatShippingAddress: (fields: any, state: string) => string;
export declare const addIfValue: (obj: any, key: string, value: any) => void;
