import { IEventListener } from "globalpayments-lib";
import "globalpayments-lib/polyfills";
import * as creditCard from "./credit-card";
import * as apm from "./apm";
import * as eCheck from "./echeck";
import * as giftAndLoyalty from "./gift-and-loyalty";
import * as internal from "./internal";
import Events from "./internal/lib/events";
import * as paymentRequest from "./payment-request";
import * as configure from "./tools/configure";
import * as ui from "./ui";
import * as enums from "./internal/lib/enums";
declare const _default: {
    configure: (options: configure.IConfiguration) => void;
    creditCard: typeof creditCard;
    apm: typeof apm;
    eCheck: typeof eCheck;
    enums: typeof enums;
    events: typeof Events;
    giftAndLoyalty: typeof giftAndLoyalty;
    internal: typeof internal;
    on: (ev: string, listener: IEventListener) => void;
    paymentRequest: typeof paymentRequest;
    ui: typeof ui;
};
export default _default;
