import { IApmConfiguration } from "../../apm/non-card-payments/contracts";
export declare const showHostedFieldValidation: (fieldId: string | null, validationMessage: string, target?: string | undefined) => void;
export declare const hideHostedFieldValidation: (fieldId: string | null, target?: string | undefined) => void;
export declare const resetValidationRoundCounter: () => void;
export declare const getValidationRoundCounter: () => number;
export declare const increaseValidationRoundCounter: () => void;
export declare const removeValidationRoundCounter: () => void;
export declare const isOpenBankingAvailable: (countryCode: string | undefined, aquirer: string | undefined) => boolean;
export declare const isBlikAvailable: (countryCode: string | undefined, currencyCode: string | undefined, options: IApmConfiguration | undefined) => boolean;
export declare const isExpressPayAvailable: (options: IApmConfiguration | undefined) => boolean | undefined;
export declare const getAvailableOptionsForBnpl: (countryCode: string | undefined, options: IApmConfiguration | undefined) => any;
